/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkBoardRouteImport } from './routes/bulk-board'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ListCropRouteImport } from './routes/list-crop'
import { Route as LogisticsRouteImport } from './routes/logistics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkBoardRoute = BulkBoardRouteImport.update({
  id: '/bulk-board',
  path: '/bulk-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ListCropRoute = ListCropRouteImport.update({
  id: '/list-crop',
  path: '/list-crop',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-board': typeof BulkBoardRoute
  '/forecast': typeof ForecastRoute
  '/list-crop': typeof ListCropRoute
  '/logistics': typeof LogisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-board': typeof BulkBoardRoute
  '/forecast': typeof ForecastRoute
  '/list-crop': typeof ListCropRoute
  '/logistics': typeof LogisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-board': typeof BulkBoardRoute
  '/forecast': typeof ForecastRoute
  '/list-crop': typeof ListCropRoute
  '/logistics': typeof LogisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/bulk-board' | '/forecast' | '/list-crop' | '/logistics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/bulk-board' | '/forecast' | '/list-crop' | '/logistics'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bulk-board'
    | '/forecast'
    | '/list-crop'
    | '/logistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BulkBoardRoute: typeof BulkBoardRoute
  ForecastRoute: typeof ForecastRoute
  ListCropRoute: typeof ListCropRoute
  LogisticsRoute: typeof LogisticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-board': {
      id: '/bulk-board'
      path: '/bulk-board'
      fullPath: '/bulk-board'
      preLoaderRoute: typeof BulkBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-crop': {
      id: '/list-crop'
      path: '/list-crop'
      fullPath: '/list-crop'
      preLoaderRoute: typeof ListCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BulkBoardRoute: BulkBoardRoute,
  ForecastRoute: ForecastRoute,
  ListCropRoute: ListCropRoute,
  LogisticsRoute: LogisticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
